name: Build and Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        node: [ 22 ]
    runs-on: ubuntu-latest
    name: Astro Check for Node.js ${{ matrix.node }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.22.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Astro Check
        run: pnpm astro check
        env:
          ENABLE_CONTENT_SYNC: false

  build:
    strategy:
      matrix:
        node: [ 22 ]
    runs-on: ubuntu-latest
    name: Astro Build for Node.js ${{ matrix.node }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.22.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Astro Build
        run: pnpm astro build
        env:
          ENABLE_CONTENT_SYNC: false
